e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ebiyung/', include('main.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import * #edit_product, delete_product, add_product_entry_ajax




app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('model/', show_model_main, name='show_model_main'),
    path('static/', show_static_main, name='show_static_main'),
    path('create-product-entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-mood/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'), # sesuaikan dengan nama fungsi yang dibuat
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('add-product-entry-ajax/', add_product_entry_ajax, name='add_product_entry_ajax'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.

class ProductEntry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10 , decimal_places=3)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to='products/', null=True, blank=True)

def __str__(self):
    return self.firstname

main/forms.py
from django.forms import ModelForm
from main.models import ProductEntry
from django.utils.html import strip_tags

class ProductEntryForm(ModelForm):
    class Meta:
        model = ProductEntry
        fields = ["name", "price", "description"]

    def clean_product(self):
        product = self.cleaned_data["product"]
        return strip_tags(product)

    def clean_price(self):
        price = self.cleaned_data["price"]
        return strip_tags(price)
    
    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
import datetime
from django.urls import reverse
from django.shortcuts import render, redirect, reverse
from main.forms import ProductEntryForm
from main.models import ProductEntry
from .models import ProductEntry
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse
from django.views.decorators.http import require_POST

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {'name': request.user.username, 'last_login': request.COOKIES['last_login']}
    return render(request, "main.html",context)

def show_model_main(request):

    # context = ProductEntry.objects.all()
    
    return render(request, "model_main.html") 
# {'context' : context}

def show_static_main(request):
    return render(request, "static_main.html")

def create_product_entry(request):
    form = ProductEntryForm(request.POST or None)

    if form.is_valid and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')
    
    context = {'form': form}
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product entry berdasarkan id
    product = ProductEntry.objects.get(pk = id)

    # Set product entry sebagai instance dari form
    form = ProductEntryForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get product berdasarkan id
    product = ProductEntry.objects.get(pk = id)
    # Hapus product
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = ProductEntry.objects.create(
            user=request.user,
            product=data["product"],
            price=int(data["price"]),
            description=data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    if request.method == 'POST' and request.is_ajax():
        data = json.loads(request.body)
        product = data["product"]
        description = data["description"]
        price = data["price"]
        user = request.user

        new_product = ProductEntry(
            product=product, 
            description=description,
            price=price, 
            user=user
        )
        new_product.save()

        return JsonResponse({"status": "success"}, status=200)

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    {% endblock meta %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Biyung</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'main:show_main' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:show_model_main' %}"
                >History</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Menu
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'main:show_static_main' %}">Food</a></li>
                <li><a class="dropdown-item" href="#">Beverages</a></li>
              </ul>
            </li>
          </ul>

          <div class="form-inline my-2 my-lg-0">
            <a href="{% url 'main:login' %}" class="btn btn-primary">Login </a>
          </div>
        </div>
      </div>
    </nav>

    <div style="padding-left: 16px">
      {% block content %} {% endblock content %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfG"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

main/templates/create_product_entry.html
{% extends 'base.html' %} 

{% block meta %}
<title>Add New Product</title>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title mb-4">Add New Product Entry</h1>

          <form method="POST">
            {% csrf_token %}
            <table>
              {{ form.as_table }}
              <tr>
                <td></td>
                <td>
                  <input type="submit" value="Add Product Entry" />
                </td>
              </tr>
            </table>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %} {% load static %} {% block content %}

<h1>Edit Product</h1>

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Edit Product" />
      </td>
    </tr>
  </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %} {% block meta %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="login.css">
    <title>Login</title>
</head>

{% endblock meta %} {% block content %}
<div class="container d-flex justify-content-center align-items-center min-vh-100">
  <div class="row border rounded-5 p-5 bg-gradient shadow-lg box-area" style="width: 100%; max-width: 700px;">
    <div class="col-md-12 d-flex justify-content-center align-items-center flex-column">
      <div class="outer-box w-100">
        <div class="login-box text-center d-flex flex-column justify-content-center align-items-center h-100 w-100">
          <h1 class="card-title text-center mb-4">Login</h1>

          <div class="input-group mb-3 text-center">
            <form method="POST" action="" class="w-100">
              {% csrf_token %}
              <div class="form-group mb-3">
                <input type="text" name="username" class="form-control" placeholder="Username">
              </div>
              <div class="form-group mb-3">
                <input type="password" name="password" class="form-control" placeholder="Password">
              </div>
              <div class="input-group mb-5 d-flex justify-content-between">
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="formCheck">
                  <label for="formCheck" class="form-check-label text-secondary"><small>Remember Me</small></label>
                </div>
                <div class="forgot">
                  <small><a href="{% url 'main:register' %}">Forgot Password?</a></small>
                </div>
              </div>
              <div class="input-group mb-3">
                <!-- <button class="btn btn-lg btn-primary w-100 fs-6" type="submit" value="Login">Login</button> -->
                <input class="btn btn-lg btn-primary w-100 fs-6" type="submit" value="Login">
              </div>
              <div class="row">
                <small>Don't have an account? <a href="{% url 'main:register' %}">Register Now</a></small>
              </div>
              <!-- <table>
                <tr>
                    <td>
                        <input type="text" name="username" class="form-control" placeholder="Username">
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </td>
                </tr>
                <tr>
                    <td>
                        <input class="btn btn-primary" type="submit" value="Login">
                    </td>
                </tr>
              </table> -->
            </form>
          </div>

          {% if messages %}
          <div class="d-grid">
            <ul class="list-unstyled">
              {% for message in messages %}
              <li class="alert alert-info">{{ message }}</li>
              {% endfor %}
            </ul>
            {% endif %}

            <!-- <div class="mt-3 text-center">
              Don't have an account yet?
              <a href="{% url 'main:register' %}">Register Now</a>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} {% block content %} 

{% load static %}

<html lang="en">
  <head>
    {% block meta %}
    <title>Biyung Cafe Home - Items Ordered</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<<<<<<< HEAD
    {% endblock meta %}
=======
    <style>
      .card {
        width: 300px;
        border: 1px solid;
      }

      .card img {
        width: 100%;
      }

      .card-title {
        margin: 12px;
      }

      .card-description {
        margin: 12px;
      }

      .card-button {
        color: azure;
        background-color: blue;
        border: none;
        border-radius: 5px;
        margin: 12px;
        padding: 10px 20px;
        text-align: left;
      }
    </style> 
>>>>>>> e77869b (Tugas 9)
  </head>
  <div class="container mt-5">
    <h1 class="text-center text-light">Welcome to Biyung Cafe</h1>
    <h2 class="text-center text-light">Where Flavor Meets Divine</h2>
    <h3 class="text-center text-light">Welcome {{ name }} !</h3>

    <div class="card">
      <img src="https://acushnet.scene7.com/is/image/titleist/2024AVX-PDP-5050-Final?wid=1200&qlt=75&resMode=sharp2" alt="Card Image">
      <div class="card-title"><h2>Golf Ball<h2></div>
      <div class="card-description">This is a golf ball</div>
      <button class="card-button">Hit the Ball</button>
    </div> 
  </div>
</html>

<div id="product_entry_cards">
  <div id="crudModal" tabindex="-1" aria-hidden="true" class="modal fade" role="dialog">
    <div id="crudModalContent" class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <!-- Modal header -->
        <div class="modal-header">
          <h5 class="modal-title">Add New Product Entry</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="closeModalBtn">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
          <form id="productEntryForm">
            <div class="form-group">
              <label for="product" class="col-form-label">Product</label>
              <input type="text" id="product" name="product" class="form-control" placeholder="Enter your product" required>
            </div>
            <div class="form-group">
              <label for="price" class="col-form-label">Price</label>
              <textarea id="price" name="price" rows="3" class="form-control" placeholder="Enter the Price" required></textarea>
            </div>
            <div class="form-group">
              <label for="Description" class="col-form-label">Description)</label>
              <input type="text" id="description" name="description" class="form-control" required>
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="cancelButton">Cancel</button>
          <button type="submit" form="productEntryForm" class="btn btn-primary" id="submitProductEntry">Save</button>
        </div>
      </div>
    </div>
  </div>
  
</div>

<div>
  <a href="{% url 'main:create_product_entry' %}" >
    <button type="button" id="addProductBtn" class="btn btn-success font-weight-bold my-3 mx-3 rounded-lg ">Add New Product Entry</button>
  </a>
  <button type="button" id="addProductByAjaxBtn" class="btn btn-primary font-weight-bold my-3 mx-3 rounded-lg" data-bs-toggle="modal" data-bs-target="#crudModal" >
    Add New Product Entry by AJAX
  </button>
  <!-- <a href="{% url 'main:logout' %}" class="btn btn-secondary">
    <button>Logout</button>
  </a> -->
</div>
<h5 style="color: aliceblue">Sesi terakhir login: {{ last_login }}</h5>

<script>
  async function getProductEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshProductEntries() {
    document.getElementById("product_entry_cards").innerHTML = "";
    document.getElementById("product_entry_cards").className = "";
    const productEntries = await getProductEntries();
    let htmlString = "";
    let classNameString = "";

    if (productEntries.length === 0) {
        classNameString = "d-flex flex-column align-items-center justify-content-center min-vh-50 p-4";
        htmlString = `
            <div class="d-flex flex-column align-items-center justify-content-center min-vh-50 p-4">
                <img src="{% static 'products/no-cheese.png' %}" alt="No Cheese" class="img-fluid mb-4" style="max-width: 8rem;"/>
                <p class="text-center text-muted mt-4">Belum ada data produk pada Biyung Cafe.</p>
            </div>
        `;
    } else {
        classNameString = "row g-4";
        productEntries.forEach((item) => {
          const product = DOMPurify.sanitize(item.fields.product);
          const price = DOMPurify.sanitize(item.fields.price);
          const description= DOMPurify.sanitize(item.fields.description);
            htmlString += `
            <div class="col-md-4">
                <div class="card shadow-sm">
                    <div class="card-header bg-primary text-white">
                        <h5 class="card-title mb-0">${product}</h5>
                        <small>${item.fields.time}</small>
                    </div>
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-muted">Price</h6>
                        <p class="card-text">${price}</p>
                        <h6 class="card-subtitle mt-4 mb-2 text-muted">Description</h6>
                        <div class="progress mb-2">
                            <div class="progress-bar bg-primary" role="progressbar" style="width: ${item.fields.description > 10 ? 100 : item.fields.description * 10}%;" aria-valuenow="${item.fields.description}" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <small class="text-muted">${description > 10 ? '10+' : item.fields.description}</small>
                    </div>
                    <div class="card-footer bg-white border-top-0">
                        <a href="/edit-product/${item.pk}" class="btn btn-warning btn-sm me-2">
                            <i class="bi bi-pencil-square"></i> Edit
                        </a>
                        <a href="/delete/${item.pk}" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash"></i> Delete
                        </a>
                    </div>
                </div>
            </div>
            `;
        });
    }
    document.getElementById("product_entry_cards").className = classNameString;
    document.getElementById("product_entry_cards").innerHTML = htmlString;
  }
  refreshProductEntries();

  const modal = new bootstrap.Modal(document.getElementById('crudModal')); // Bootstrap modal instance

  function showModal() {
      modal.show(); // Menampilkan modal menggunakan Bootstrap method
  }

  function hideModal() {
      const modal = bootstrap.Modal.getInstance(document.getElementById('crudModal'));
      if (modal) {
          modal.hide(); // Menyembunyikan modal menggunakan metode Bootstrap
      }
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);

  document.addEventListener("DOMContentLoaded", function() {
      const modal = new bootstrap.Modal(document.getElementById('crudModal'));
  
      function addProductEntry() {
        fetch("{% url 'main:add_product_entry_ajax' %}", {
          method: "POST",
          body: new FormData(document.querySelector("#productEntryForm")),
        }).then((response) => {
          if (response.ok) {
            refreshProductEntries();
            hideModal(); // Sembunyikan modal setelah menambahkan entri
          }
        }).catch((error) => console.error('Error:', error));

        document.getElementById("productEntryForm").reset();
        document.querySelector("[data-modal-toggle='crudModal']").click();

        return false;
      }
  });

  document.getElementById("submitProductEntry").addEventListener("click", addProductEntry);

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js" integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK" crossorigin="anonymous"></script>
{% endblock content %}

main/templates/model_main.html
{% extends 'base.html'%} {% block content %}
<html lang="en">
  <head>
    <title>Biyung Cafe</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <style>
      body {
        background-color: rgba(34, 11, 126, 0.876);
      }
      .center {
        font-family: Arial, Helvetica, sans-serif;
        text-align: center;
      }
      .p1 {
        font-family: Arial, Helvetica, sans-serif;
        margin-top: 5px;
      }
      .h1 {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 24px;
      }
      .h5 {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 18px;
        margin-top: 15px;
        margin-bottom: 5px;
      }
      .border {
        border: 2px solid black; 
        border-radius: 15px; 
        padding: 20px; 
        background-color: white; 
        width: 300px; 
        margin: 0 auto; 
      }
      img {
        display: block;
        max-width: 100%;
        margin-top: 5px;
      }
    </style>
  </head>
  <body>
    <h1 class="center" style="color: aliceblue">Founder of Biyung Cafe</h1>
    <h2 class="center" style="color: aliceblue">Abella Maya Santi</h2>
    <h2 class="center" style="color: aliceblue">PBP B</h2>
  </body>
</html>

<div class="row">
  {% for c in context %}
  <div class="col">
    <div class="card" style="width: 18rem">
      <img src="{{ c.image }}" class="card-image" alt="" />
      <div class="card-body">
        <p class="card-text">Rp{{ c.price }}</p>
        <h5 class="card-title">{{ c.name }}</h5>
        <h6 class="card-description">{{ c.description }}</h6>
      </div>
    </div>
  </div>
  {% endfor %} {% endblock content %}
</div>

main/templates/register.html
{% extends 'base.html' %} {% block meta %} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="login.css">
    <title>Register</title>
</head>

{% endblock meta %} {% block content %}
<div class="container d-flex justify-content-center align-items-center min-vh-100">
  <div class="row border rounded-5 p-5 bg-gradient shadow-lg box-area" style="width: 100%; max-width: 700px;">
    <div class="col-md-12 d-flex justify-content-center align-items-center flex-column">
      <div class="outer-box w-100">
        <div class="login-box text-center d-flex flex-column justify-content-center align-items-center h-100 w-100">
          <h1 class="card-title text-center mb-4">Register</h1>

          <div lass="input-group mb-3 text-center">
            <form method="POST" action="" class="w-100">
              {% csrf_token %}
              <div class="form-group mb-3">
                {{ form.non_field_errors }}
                <!-- Username Field -->
                <input type="text" name="{{ form.username.name }}" placeholder="Username" class="form-control" required id="{{ form.username.id_for_label }}">
              </div>
  
              <div class="form-group mb-3">
                <!-- Password Field -->
                <input type="password" name="{{ form.password1.name }}" placeholder="Password" class="form-control" required id="{{ form.password1.id_for_label }}">
              </div>
  
              <div class="form-group mb-3">
                <!-- Password Confirmation Field -->
                <input type="password" name="{{ form.password2.name }}" placeholder="Confirm Password" class="form-control" required id="{{ form.password2.id_for_label }}">
              </div>
  
              <div class="input-group mb-3">
                <input
                        class="btn btn-lg btn-primary w-100 fs-6"
                        type="submit"
                        value="Register"
                      />
              </div>
                <!-- <table>
                  <tr>
                    <td d-grid>
                      <input
                        class="btn btn-primary"
                        type="submit"
                        value="Register"
                      />
                    </td>
                  </tr>
                </table> -->
            </form>
          </div>

          {% if messages %}
          <div class="mt-3">
            <ul class="list-unstyled">
              {% for message in messages %}
              <li class="alert alert-info">{{ message }}</li>
              {% endfor %}
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}